name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-void:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.14', '1.15', '1.16', '1.17', '1.18']

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'

      - name: Test without tags
        run: make test

      - name: Test with noxlib tag
        run: make test TAGS=noxlib

      - name: Test with noutmp tag
        run: make test TAGS=noutmp

      - name: Test with nopam tag
        run: make test TAGS=nopam

      - name: Build with noxlib tag
        run: |
          # Make clean
          make clean
          # Make build
          make build TAGS=noxlib

      - name: Build with noutmp tag
        run: |
          # Make clean
          make clean
          # Make build
          make build TAGS=noutmp

      - name: Build with nopam tag
        run: |
          # Make clean
          make clean
          # Make build
          make build TAGS=nopam

      - name: Build without tags
        run: |
          # Make clean
          make clean
          # Make build
          make build

      - name: Test install-pam
        run: make install-pam

      - name: Test install-manual
        run: make install-manual

      - name: Test install-config
        run: make install-config

      - name: Test install-runit
        run: make install-runit

      - name: Test install-motd-gen
        run: make install-motd-gen

      - name: Test install
        run: make install

      - name: Test uninstall
        run: make uninstall
